### ISSUE TITLE
Follow-up 3129

### ISSUE THREAD

**Issue by dannywillems** [o1-labs/proof-systems#3140]
FYI, these features are already in the workspace and features are additive, so all of these are redundant

You can also write this as 
```toml
[dependencies.web-sys]
workspace = true
features = [
    "X",
    "Y",
]
```
which I think looks a little cleaner

_Originally posted by @richardpringle in https://github.com/o1-labs/proof-systems/pull/3129#discussion_r2027239928_
