### ISSUE TITLE
Make sure one can easily use the library from the README

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#527]
There's a few things that we should do:

* make sure the code example in README is run as test in cargo (so it doesn't break)
* give some guidelines on how to use this library

right now you have to import things like this:

```toml
[dependencies]
kimchi = { git = "https://github.com/o1-labs/proof-systems" }
mina-curves = { git = "https://github.com/o1-labs/proof-systems" }
oracle = { git = "https://github.com/o1-labs/proof-systems" }
commitment_dlog = { git = "https://github.com/o1-labs/proof-systems" }
```

which imo is not clean. Kimchi should re-export these crates so you don't have to import them yourself
